{% set version = "0.18" %}

package:
  name: otfftw
  version: {{ version }}

source:
  fn: otfftw-{{ version }}.tar.gz
  url: https://github.com/openturns/otfftw/archive/v{{ version }}.tar.gz
  sha256: 76b854f95e2f3e9278274352b6134321943838a1e3c7420408b29bc8137647b2

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('otfftw', max_pin='x.x') }}
  python_version_independent: true  # [is_abi3]
  skip: True  # [is_abi3 and not is_python_min]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python-abi3  # [is_abi3]
    - python
    - fftw
    - openturns
  run:
    - python

test:
  requires:
    - abi3audit  # [is_abi3]
  imports:
    - otfftw
  commands:
    - abi3audit $SP_DIR/otfftw/_otfftw.so -s -v --assume-minimum-abi3 3.10  # [unix and is_abi3]

about:
  home: http://openturns.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: FFTW module

extra:
  recipe-maintainers:
    - jschueller
