{% set version = "0.5" %}
{% set ot_version = "1.10" %}

package:
  name: otfftw
  version: {{ version }}

source:
  fn: otfftw-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otfftw/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

  fn: otfftw-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

  fn: otfftw-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

  fn: otfftw-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

  fn: otfftw-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

  fn: otfftw-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

  fn: otfftw-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317

build:
  number: 0

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]
    - fftw  # [not win]

  run:
    - python
    - openturns
    - fftw  # [not win]

test:
  imports:
    - otfftw

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: FFTW module

extra:
  recipe-maintainers:
    - jschueller
