{% set version = "0.5" %}
{% set ot_version = "1.11rc1" %}

package:
  name: otfftw
  version: {{ version }}

source:
  fn: otfftw-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otfftw/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 582c6d99971cf72129caf74544b4fe9b706c22038aaac7ba52f3b0a396c50317  # [not win]

  fn: otfftw-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: eb6f39fa6fa404c38b9d28d5b94d3e6c7d28f2b9573972274cbcb18fa5404f34  # [win64 and py27]

  fn: otfftw-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 2da3a675320f0cefccf64e031d4be600146cff585bf1faf188b7d471ec58a43e  # [win64 and py35]

  fn: otfftw-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otfftw-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 44def0fbbe69973d5765cf2728f3ca738ec569f40da0f76558696ede4b0321c1  # [win64 and py36]

build:
  number: 1

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
    - fftw  # [not win]
  run:
    - python
    - openturns
    - fftw  # [not win]

test:
  imports:
    - otfftw

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: FFTW module

extra:
  recipe-maintainers:
    - jschueller
