{% set version = "0.9" %}

package:
  name: otfftw
  version: {{ version }}

source:
  fn: otfftw-{{ version }}.tar.gz
  url: https://github.com/openturns/otfftw/archive/v{{ version }}.tar.gz
  sha256: 5743861e4f69c75d08d99f781d7f6db3a7e77639609ae10866c12ac176a97780

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otfftw', max_pin='x.x') }}

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns
    - fftw  # [not win]
  run:
    - python
    - openturns
    - fftw  # [not win]

test:
  imports:
    - otfftw

about:
  home: http://openturns.org/
  license: GPL3
  license_file: COPYING
  summary: FFTW module

extra:
  recipe-maintainers:
    - jschueller
