{% set version = "0.10" %}

package:
  name: otfftw
  version: {{ version }}

source:
  fn: otfftw-{{ version }}.tar.gz
  url: https://github.com/openturns/otfftw/archive/v{{ version }}.tar.gz
  sha256: be54727f8e36a73c3927589c854ff743851203503dd0bdf5d40da7d44992e00e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otfftw', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - fftw  # [not win]
    - openturns 1.15*
  run:
    - python
    - fftw  # [not win]
    - openturns 1.15*

test:
  imports:
    - otfftw

about:
  home: http://openturns.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: FFTW module

extra:
  recipe-maintainers:
    - jschueller
