# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Vka5vPv54izVwGhNfc96/xLm7v2vTjM2zcg8UDrl5aA9jXumHueaLpJ4f+/66A+T9HqQKrVrNQ7mnatM/kOzx3T6NV61jleSwHqxdHCrKKpVsM4m+6LvxNcubRnj3qgY05tfrri1D7IQslGMLOhIKHaivzrMQMIGFW9TitN9XQo+7n+28BApJ1gRFlaOd+qXYe1g1dhMg46i4W6qDpTi/HkkY74JipbWPZrPv/qSNCHqrOq0dht2JRVlKc3xvDD9iXR/edj9e+GyFXFAJB/8Jb+x2iSHKKoYcGuuQ/zGdbRnztoWA1cD0A+at3G9ytFyB3YcXNu0I6tS+Sz7Fx6FjVoXnwZovPRamIOIWa+lGxBXLAooaJyJFC1gl3n7PC0dgVYRUlGX0+Zn5Y+gLI274dYWmF972zAhHxKlGiDLQqrcvwZEaoiPXZ3SvfQlhR/4OdDPaihta+MuBAmUU12D5TTtxi0n/MkKPB2nYLdlVANsDeTIVflQS3gr2w6cJybItV2zNEF1oH+JfliYCxldaLMonA0Qt+RYdHyzOeQul6ZTdsO2dlNLFmgl9D8bUrM8a/ztXor9Sq3wR5Utq35vpL7cM3pAr8LWJ4EvmoPJ90maLZD1tfjvORgQKowpBZZ9g3Jj/mW1cb3FImeDCii+0LYRDCfEDBBniidOAXNUDtA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
