travis:
  secure:
    BINSTAR_TOKEN: DDlZLvOsfxRJnJFY9cRQ/B9ttBCR0dqQCNljsnGrgrQ4Du02S1ghI4dN3/ISmn7OpzIyMi6t/uvEExu8ZkJfbSoCWvX30SlRmLMbmfDN7kW5wAWvInkWOQFIgvvYU9QGkWi+Q2pVt3O+QYCGVe/i7ieG4bWNlPLfqHIX7ppzngR5ozrW/NelNGdrBD9tkoQ2iV7fmutZy91sXQkE7pJry0D9ctZ8u1mfUEvnUnydSMwTaSjySKRi8azMQMonGdYcQEDydxe6WXI4hNzeFJgK1pP2eYmO9R/D8d7H/RIRbTU2YKmEJ6D/7JVp0qdjqjAvAaEjR+xtgw2DIys91G4onpa59stosJn5qqJ5Dv5+pKlZ4DCqUeJCenb3BkVZsEiVXO0uzc+/4S5upL3/ogmdTXJO4tSRa8yLEbarFaAMnqGdKas1th7WelySav8F1BbHRAvwp7zDJ6vkAIbo/aREUN1hCtkBg/vat1U2FdUTpvvwAK7fbTkun7nR9QsfsZ/I3Z8DuyxtdVdCVXJB0pkkeNuqUUa5gZ2blImb4zoPgF3EkjrImUp+YNkOKbgvWzajiXaOBjuymhkxXfNEeovWoool1uhdicccGhs5BDG0oMX/qcPd5BfUjRmFRx4EDV0kNQCvorT1nFNUgEzEnUsyhGS5nHdrgVqOq9QmAzU2I4M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
