appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BIHiaRoU5CrA7lnk5e5tlUK5/8494mVKpNw0nwKaQdTRakTBEAAM2tQDPNIKtsjWXwTMpI9oK5kL2osItfZ9xstzzomm2fBpcynIYs1GoQrtV2FlfdCuz505N2ZTgcVsfcaqT3jgfE9Hta44t+pWbuRUdHdVlMC0voZ3z9NSn8bmCdQhAaY60Jlw0ab3UVLwBln/QvlGHdd5E5WG65R0R+wpmcoexTAh+FDhX4cOxqZVuQwu81k61yo8lrOL6bR3+4in8nSOrvQXKYc6g1Pc23YmpzoG0ym9EJ6kp04498XbVUhLFnwoZbDzKDka7wR30SgduIduQlwO9FyqB7Kmq7gLIH4cdGDum+rDaotKga58uNzZxeNYCXu1mPwdb5okJn1mNTfLmEIW7N3W4fK1BtUTxm4ok0ivSABvvZJTCbPNVbohwf9B0/r8PJG7NXs0HsixfHF2y/8DzOQsLo9ovXyrtplVzZPzgI48xd4kOhN/+e3uha1x/TDGv4L/CglGwCAHiikhx8pY8Ol99ku6SjJNIpZ63tOKFxOr6Z0UOouPHXUMb8eE8aKDm1qYtL30h/D5qwn8zMuGpm1VaIY8UGGKb49Vur9LGs8x4eADx6zpRnFMlQxGBBn4oA2uRz4LLPJubghvrpZnZUzKq9SMjDV2Tpu2+MAJqls7KW3Gl+g=}
provider:
  win: azure
conda_forge_output_validation: true
