travis:
  secure:
    BINSTAR_TOKEN: RRNSqTtir835MHldZ7uHukzZMRq/JAGPifk2XbIVqFjjxklhFG93acYml5RHRqRW5lU/VKnAF2Cfo3kMRWJ8sFjm+pu9I2nigTmtTP7Knehf6qPX1FVAQnPQYwoSe1vc/Ztv/+39Ha4WatcyhIuRn4qeo2fUCEdWsWgkbXlcgiVB3skd0faiq2OfevuDoGivZLuVdBfxy0FBNFkpzkc4KcAeP43PdioowDMGts6L1fN07Gj6Hs5wvZ/GEengeJk9B4ChvRZgol0crrr7lEhk9kaAn6UtQjGNbfDjR0hShT4Rl4lHyfzCslXuFEv7td46Ps9kBaBfIWb1CnrmtJ3Aa06A9NeoA8B3GROJwFZQGX8ftEQ1sBCLTvsoGSxcdodEGxjRbXP8qiOv3I1O77iFqxj7fFWgRaKlYGylgqxApLFowGYB6B0frsDN6NLCzUB/vdxvDbU1/hjyYU88JwUdGYKQ3F3lhguJn+xZT/T9+b5tCfP6my2LV+ZHr6XQNjV1fjVmq7OsSsYPAn9oAFWm3zB0j/Wa2J24kxTZt6mkw7I/QOwxMVorlIZy4qBmicT1GRnQuRg6tF7oyKBqffhoZSrNn6n/cMZ7/G50LdeCOfXRByVB2z3r5AEJwkwY52ZtwDFQVq8YmBXBIMnbM/OcCGZysthSgpD5Z0V5ph54CjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
